[package]
name = "dora-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# actix-web = "4"
kyber-rs = { path = "../kyber-rs" }
anyhow = "1.0.68"
thiserror = "1.0.38"
futures = "0.3.25"
async-std = "1.12.0"
async-trait = "0.1.60"
