version: '3'

services:
  minio-1:
    container_name: minio
    image: minio/minio
    stop_grace_period: 5m
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data


  dora-storage-1:
    container_name: d1
    image: giordyfish/test-dora-storage:latest
    stop_grace_period: 5m
    restart: always
    depends_on:
      minio-1:
        condition: service_started
    command:
      - "--storage=minio-1:9000"
      - "dora-storage-2:9000"
      - "dora-storage-3:9000"
      - "-p=9000"

  dora-storage-2:
    container_name: d2
    image: giordyfish/test-dora-storage:latest
    stop_grace_period: 5m
    restart: always
    depends_on:
      minio-1:
        condition: service_started
    command:
      - "--storage=minio-1:9000"
      - "dora-storage-1:9000"
      - "dora-storage-3:9000"
      - "-p=9000"

  dora-storage-3:
    container_name: d3
    image: giordyfish/test-dora-storage:latest
    stop_grace_period: 5m
    restart: always
    depends_on:
      minio-1:
        condition: service_started
    command:
      - "--storage=minio-1:9000"
      - "dora-storage-1:9000"
      - "dora-storage-2:9000"
      - "-p=9000"


#### minio volumes
volumes:
  minio_storage: {}   